<?php
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>


<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(''. $this->translate('Nir Goldman'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/website/favicon-website.ico'))
                        ->prependStylesheet($this->basePath() . '/css/website.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body id="<?php echo $this->translate('English-Layout')?>">

    <div class="navbar navbar-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="public/img/website/logo.png" alt="logo"/>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a traget="_blank" href="<?php echo $this->url('Website', array('action' => 'index')); ?>">Home</a></li>
                    <li><a traget="_blank" href="<?php echo $this->url('Website', array('action' => 'about')); ?>">About</a></li>
<!--                    <li><a traget="_blank" href="--><?php //echo $this->url('Website', array('action' => 'contact')); ?><!--">Contact</a></li>-->
                    <li><a traget="_blank" class="bold-menu" href="<?php echo $this->url('Website', array('action' => 'zf2Projects')); ?>">ZF2 Projects</a></li>
                </ul>
            </div><!--/.navbar-collapse -->
        </div>
    </div>




<!--    start:HERE PUT THE CONTENT-->
    <div class="bigContainer">
            <?php echo $this->content; ?>
            <hr>
            <footer>
<!--                    <h1>this is the Right Place !!</h1>-->
            </footer>
        </div> <!-- /container -->
<!-- end:HERE PUT THE CONTENT-->

