<div id="indexPage">

  <div class="background_gray_wash_wall">

     <div class="row">
        <div class="col-lg-12">
                <div class="flexslider marginTop40">
                    <ul class="slides">
                        <li>
                            <img src="/public/img/start-tech/slider-home-page/slider001.jpg" />
                        </li>            <li>
                            <img src="/public/img/start-tech/slider-home-page/slider002.png" />
                        </li>            <li>
                            <img src="/public/img/start-tech/slider-home-page/slider003.png" />
                        </li>            <li>
                            <img src="/public/img/start-tech/slider-home-page/slider004.png" />
                        </li>

                    </ul>
                </div>
        </div>
      </div>

  </div>


    <div class="h-zigzag "></div>


    <div class="background_title_black">

        <div class="row borderBottomTitle">
            <div class="col-lg-4"></div>
            <div class="col-lg-4 ">
                <h1 class="purple marginRight92 marginTopBottom44  neon">

                        ברוכים הבאים ל StartTech
                </h1>

            </div>
            <div class="col-lg-4"></div>
        </div>
    </div>

<div class="background-subtle-white-feathers">

    <div class="container">


    <div class="row">
        <div class="col-lg-6"></div>
        <div class="col-lg-6">
            <div class="col-lg-1"></div>
            <div class="col-lg-11">
                <h2 class="darkPurple">
                    <span>
                       <img src="/public/img/start-tech/about_arrow_up.png" alt=""/>

                    </span>
מי אנחנו?
                </h2>
                <p>לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית. סת אלמנקום ניסי נון ניבאה. דס איאקוליס וולופטה דיאם. וסטיבולום אט דולור, קראס אגת לקטוס וואל אאוגו וסטיבולום סוליסי טידום בעליק. קונדימנטום קורוס בליקרה, נונסטי קלובר בריקנה סטום, לפריקך תצטריק לרטי. </p>

            </div>
    </div>
    </div>

    <div class="row">
        <div class="col-lg-6"></div>
        <div class="col-lg-6">
            <div class="col-lg-1"></div>
            <div class="col-lg-11">
                <div >
                    <h2 class="darkPurple">
                    <span>
                       <img src="/public/img/start-tech/about_arrow_up.png" alt=""/>
                    </span>
החזון שלנו
                    </h2>
                </div>
                <p>לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית. סת אלמנקום ניסי נון ניבאה. דס איאקוליס וולופטה דיאם. וסטיבולום אט דולור, קראס אגת לקטוס וואל אאוגו וסטיבולום סוליסי טידום בעליק. קונדימנטום קורוס בליקרה, נונסטי קלובר בריקנה סטום, לפריקך תצטריק לרטי. </p>
        </div>
    </div>
    </div>
        <div class="row">
            <div class="col-lg-2">
                <img class="floatLeft" src="/public/img/start-tech/logo367x87.png" alt=""/>
            </div>
            <div class="col-lg-10"></div>
        </div>
    <div class="row">
        <div class="col-lg-6"></div>
        <div class="col-lg-6">
            <div class="col-lg-1"></div>
            <div class="col-lg-11">
                <div >
                    <h2 class="darkPurple">
                    <span>
                       <img src="/public/img/start-tech/about_arrow_up.png" alt=""/>
                    </span>
היתרון שלנו על פני חברות אחרות
                    </h2>
                </div>
                <p>לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית. סת אלמנקום ניסי נון ניבאה. דס איאקוליס וולופטה דיאם. וסטיבולום אט דולור, קראס אגת לקטוס וואל אאוגו וסטיבולום סוליסי טידום בעליק. קונדימנטום קורוס בליקרה, נונסטי קלובר בריקנה סטום, לפריקך תצטריק לרטי. </p>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-lg-6"></div>
        <div class="col-lg-6">
            <div class="col-lg-1"></div>
            <div class="col-lg-11">
                <div >
                    <h2 class="darkPurple">
                    <span>
                       <img class="textAlignCenter" src="/public/img/start-tech/about_arrow_up.png" alt=""/>
                    </span>
                        גם אני תת כותרת
                    </h2>
                </div>
                <p>לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית לורם איפסום דולור סיט אמט, קונסקטורר אדיפיסינג אלית. סת אלמנקום ניסי נון ניבאה. דס איאקוליס וולופטה דיאם. וסטיבולום אט דולור, קראס אגת לקטוס וואל אאוגו וסטיבולום סוליסי טידום בעליק. קונדימנטום קורוס בליקרה, נונסטי קלובר בריקנה סטום, לפריקך תצטריק לרטי. </p>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <img src="/public/img/start-tech/responsive_index_page.png" alt=""/>
        </div>
        <div class="col-lg-3"></div>

    </div>


        <button class="cn-button" id="cn-button">+</button>
        <div class="cn-wrapper" id="cn-wrapper">
            <ul>
                <li class="icon-footer-1"><a href="https://www.facebook.com/refael.gold.3" target="_blank"><span class="icon-facebook"></span></a></li>
                <li class="icon-footer-2"><a href="skype:refaelgold?call" target="_blank"><span class="fa-skype fa"></span></a></li>
                <li class="icon-footer-3"><a href="https://plus.google.com/u/0/102501578978224362003" target="_blank"><span class="icon-google-plus"></span></a></li>
                <li class="icon-footer-4"><a href="mailto:refaelgold@gmail.com" target="_blank"><span class="icon-inbox"></span></a></li>
                <li class="icon-footer-5"><a href="https://twitter.com/refaelgold"><span class="icon-twitter" target="_blank"></span></a></li>
            </ul>
        </div>
        <div id="cn-overlay" class="cn-overlay"></div>

 </div>
</div>


