<div id="cv">

    <div class="row marginTop14 worldImageContainer bubble">
        <span class="col-lg-4"></span>
   <span class="col-lg-4">
       <h1 class="textAlignCenter greetingH1">Hello World !</h1>
   </span>
        <span class="col-lg-4"></span>
    </div>


<div class="container bubble">
    <div class="row">
                <span class="col-lg-5">
                    <h1 class="code_pro_title">Nir Goldman</h1>
                    <ul class="cv_list">
                        <li><span class="title_cv_span">Year of birth : </span><span>1986</span></li>
                        <li><span class="title_cv_span">Email : </span><span>refaelgold@gmail.com</span></li>
                        <li><span class="title_cv_span">Address : </span><span>Ben Yeuda , Tel Aviv,Israel</span></li>
                        <li><span class="title_cv_span">Phone : </span><span>+972-58-6275326</span></li>

                    </ul>
                </span>

    <span class="col-lg-3"></span>

                <span class="col-lg-4 marginTop49">
                    <span class="image-wrap" style="position:relative; display:inline-block; background:url('public/img/website/cv/cv.jpg') no-repeat center center; width: 150px; height: 150px;">
                        <img src="public/img/website/cv/cv.jpg" style="opacity: 0;">
                    </span>
                </span>
</div>
<div class="row">
                    <span class="col-lg-7">
                        <h2 class="title_cv">Career Objective</h2>
                        <p class="marginLeft27">
                            I would like to build a career as a Web Developer(Client side+Server side).
                            In Addition  , I gained from my course and experience some skills about web development.
                            Most of my skills come from self-learning and My believes that the combination of knowledge and motivation
                            is the most important keys for Perfect and Successful Programming.
                        </p>
                    </span>
    <span class="col-lg-5"></span>
</div>
<div class="row">
                    <span class="col-lg-12">
                        <h2 class="title_cv marginLeft30">Education</h2>
                        <ul class="cv_list" >
                            <li><span class="title_cv_span">Web Master(2012)  - </span><span> PHP,HTML5,CSS3,JS,jQuery,MySQL,PHOTOSHOP</span></li>
                            <li><span class="title_cv_span">Open University(2010-2011)- </span><span> Intro to Java Programming,Linear algebraic , Infinite Math</span> </li>
                            <li><span class="title_cv_span">High School(2001-2004) - </span><span> Computer Science class</span></li>
                        </ul>
                    </span>
</div>
<div class="row">
                    <span class="col-lg-7">
                        <h2 class="title_cv">Experience</h2>
                        <ul class="cv_list" >
                            <li>
                                <span class="title_cv_span">eWave 2013 - </span><span>
                                I build a project on Pelephone company who called "Self Service".
                                The project is a UI for client in pelephone to so action like:
                                block phone calls,send an SMS , address update , payment section and more.
                                i did  the full Client side of this project with full immigration to Spring java framework.
                                <a href="https://www.pelephone.co.il/digital/3G/Corporate/digital/homepage/.aspx">Pelephone Website</a>.

                            </span>
                            </li>
                            <li><span class="title_cv_span">Robin (2012) - </span>
                                <span>I work on Magento Development and use technologics like GIT,vagrant , Virtual box.
                                      In addition ,i have skilled of using the frontend development(PHP) and
                                      content management via administrator  panel and add extensions to Magento platform.
                                      Also i use wordpress platform for some website from psd

                                    <h5>website for example: </h5>
                                    <ol>
                                        <li> <span class="resetCss">I did some fix in level of DB and Client programming in </span> <a href="http://www.asteriadiamonds.com/">Asteria Diamonds</a></li>
                                        <li><span class="resetCss">i build this landing page for Colmobile </span><a href="http://expimltd.co.il/temp/colmobile/hyundai-ix35_feb27/">Colmobile Mini-site</a></li>
                                        <li><span class="resetCss">A website based on Wordpress Platform for example is </span><a href="http://www.romabest.co.il/">Roma Best</a></li>
                                    </ol>
                                </span>
                            </li>
                        </ul>
                    </span>
    <span class="col-lg-5"></span>
</div>
<div class="row">
                    <span class="col-lg-12">
                        <h2 class="title_cv marginLeft30">Tools(optional)</h2>
                        <ul class="cv_list" >
                            <li><span class="title_cv_span">Graphics tools - </span><span>Photoshop(primary) , GIMP.</span></li>
                            <li><span class="title_cv_span">Operating System -</span> <span>Ubuntu 13.04(primary) , mac OS ,windows 7.</span></li>
                            <li><span class="title_cv_span">Code editor - </span><span>Phpstorm6(primary) ,visual studio. </span></li>
                        </ul>
                    </span>
</div></div>
</div>