<div id="cv">

    <div class="row marginTop14 worldImageContainer bubble">
        <span class="col-lg-4"></span>
   <span class="col-lg-4">
       <h1 class="textAlignCenter greetingH1">Hello World !</h1>
   </span>
        <span class="col-lg-4"></span>
    </div>

<div class="container bubble">
    <div class="row">
                <span class="col-lg-5">
                    <h1 class="code_pro_title">Nir Goldman</h1>
                    <ul class="cv_list">
                        <li><span class="title_cv_span">Year of birth : </span><span>1986</span></li>
                        <li><span class="title_cv_span">Email : </span><span>refaelgold@gmail.com</span></li>
                        <li><span class="title_cv_span">Address : </span><span>Ben Yeuda , Tel Aviv,Israel</span></li>
                        <li><span class="title_cv_span">Phone : </span><span>+972-58-6275326</span></li>
                    </ul>
                </span>

    <span class="col-lg-3"></span>

                <span class="col-lg-4 marginTop49">
                    <span class="image-wrap" style="position:relative; display:inline-block; background:url('public/img/website/cv/cv.jpg') no-repeat center center; width: 150px; height: 150px;">
                        <img src="public/img/website/cv/cv.jpg" style="opacity: 0;">
                    </span>
                </span>
                </div>



<div class="row">
                    <span class="col-lg-7">
                        <h2 class="title_cv">Career Objective</h2>
                        <p class="marginLeft27">
                            I would like to build a career as a Web Developer (Client side+Server side).
                            In Addition, I gained from my courses and experience many skills concerning web development.
                            Most of my skills come from self-learning and I believe that the combination of knowledge and motivation
                            is the most important key for innovative and successful programming.
                        </p>
                    </span>
    <span class="col-lg-5"></span>
</div>
<div class="row">
                    <span class="col-lg-12">
                        <h2 class="title_cv marginLeft30">Education</h2>
                        <ul class="cv_list" >
                            <li><span class="title_cv_span">Web Master(2012)  - </span><span> PHP,HTML5,CSS3,JS,jQuery,MySQL,PHOTOSHOP</span></li>
                            <li><span class="title_cv_span">Open University(2010-2011)- </span><span> Intro to Java Programming,Linear algebraic , Infinite Math</span> </li>
                            <li><span class="title_cv_span">High School(2001-2004) - </span><span> Computer Science class</span></li>
                        </ul>
                    </span>
</div>
<div class="row">
                    <span class="col-lg-7">
                        <h2 class="title_cv">Experience</h2>
                        <ul class="cv_list" >
                            <li>
                                <span class="title_cv_span">eWave 2013 - </span><span>
                                I built a project for Pelephone called "Self Service".
                                The project is a UI for Pelephone clients that allows them to perform the following features:
                                block phone calls, send text messages, update their address and pay overdue payments.
                                I programmed the entire client side of this project with full immigration to Spring java framework.
                                <a  target="_blank" href="https://www.pelephone.co.il/digital/3G/Corporate/digital/homepage/.aspx">Pelephone Website</a>.

                            </span>
                            </li>
                            <li><span class="title_cv_span">Robin (2012) - </span>
                                <span>I work on Magento Development and use technologies such as GIT, Vagrant and Virtual Box.
                                      In addition, I master in frontend development (PHP) and
                                      content management via administrator panel and I'm able to add extensions to the Magento platform.
                                      Also I use the Wordpress platform to publish websites with PSD.

                                    <h5>website for example: </h5>
                                    <ol>
                                        <li> <span class="resetCss">I did several fixes on the DB and Client programming levels for </span> <a target="_blank" href="http://www.asteriadiamonds.com/">Asteria Diamonds</a></li>
                                        <li><span class="resetCss">I built this landing page for Colmobile </span><a target="_blank" href="http://expimltd.co.il/temp/colmobile/hyundai-ix35_feb27/">Colmobile Mini-site</a></li>
                                        <li><span class="resetCss">An example for a Wordpress-based website I created is </span><a target="_blank" href="http://www.romabest.co.il/">Roma Best</a></li>
                                    </ol>
                                </span>
                            </li>
                        </ul>
                    </span>
    <span class="col-lg-5"></span>
</div>
</div>
</div>