<div class="container bubble">
    <!--will be replaced with the aswame zend form!!!-->
    <div class="row">
        <div class="col-lg-12">
            <h3 class="underline">Form In Bootstrap 3</h3>
        </div>
        <div class="col-lg-6">

            <div class="well">

                <div class="form-group row">
                    <div class="col-lg-8">
                        <label for="first_name" class="control-label">First Name</label>
                        <input type="text" class="form-control" id="first_name" />
                    </div>
                </div>

                <div class="form-group row" id="last_name">
                    <div class="col-lg-8">
                        <label for="last_name" class="control-label">Last Name</label>
                        <input type="text" class="form-control" />
                    </div>
                </div>

                <div class="form-group row" id="username">
                    <div class="col-lg-8">
                        <label for="username" class="control-label">User Name</label>
                        <input type="text" class="form-control" />
                    </div>
                </div>

                <div class="form-group row" id="password">
                    <div class="col-lg-8">
                        <label for="password" class="control-label">Password</label>
                        <input type="password" class="form-control" />
                    </div>
                </div>

                <div class="form-group row" id="password">
                    <div class="col-lg-8">
                        <a href="#" class="btn btn-success btn-small">Submit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>