<div class="container bubble">
        <div class="row">
        <div class="col-lg-12">
            <h1 class="mainTitle">Nir Goldman - Web Master</h1>
        </div>
    </div>




    <div class="row">
        <div class="col-lg-8">
            <p>
                My name is Nir Goldman  and i work as Web developer for 2 years from now.i'm really looking for a company who think big and
                leading the way . I really like to study and explore every new feature who come to the market and for this time i focus on:
            </p>

            <ul>
                <li>Zend framework 2</li>
                <li>Doctrine 2</li>
            </ul>

            <p>
                I'm a fan of Open Source and i believe about not reinventing the wheel when we programming and march to the feature.
                I'm looking for a job who think big and grow with them to the end(or at least until the exit :-) )
            </p>



            <div class="row">
                <div class="col-lg-1"></div>
                <div class="col-lg-10">
                    <h2 class="greenShadowHeadline forcePointer">That's All folks.Happy Coding !!! :-)</h2>
                </div>
                <div class="col-lg-1"></div>

            </div>

        </div>
        <div class="col-lg-1"></div>
        <div class="col-lg-2">
            <img class="circular" src="public/img/website/profile_pic.png" alt=""/>
        </div>
        <div class="col-lg-1"></div>
    </div>



    <div class="row">
        <div class="col-lg-12">
            <h1 class="paddingLeft5px">Hello HR - i been expecting to you...</h1>
            <p>
                This website is created to show some skills before hiring Me as a developer/Web Master for your company.
            </p>
            <h2 class="paddingLeft5px">the Technologies are : </h2>
            <ul>
                <li>Bootstrap 3</li>
                <li>Zend Framework 2</li>
                <li>Doctrine 2</li>
                <li>SCSS</li>
                <li>Git</li>
                <li>HTML5</li>
                <li>Jquery</li>
                <li>CoffeeScript</li>
                <li>PHP</li>
                <li>MySQL</li>
            </ul>

            <h2 class="paddingLeft5px">The Tools are : </h2>
            <ul>
                <li>Design : Photoshop CC</li>
                <li>SVN : GIT</li>
                <li>IDE : phpstorm 7</li>
                <li>OS : Ubuntu 13.10</li>
                <li>VM : Vagrant</li>
            </ul>


        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">

            <h2 class="paddingLeft5px">Keep In touch</h2>
            <ul class="inline">
                <a target="_blank" href="https://www.facebook.com/refael.gold.3"><img class="rotate" src="public/img/website/social_icons/facebook.png" alt=""/></a>
                <a target="_blank" href="skype:refaelgold?call"><img class="rotate" src="public/img/website/social_icons/skype.png" alt=""/></a>
                <a target="_blank" href="https://twitter.com/refaelgold"><img class="rotate" src="public/img/website/social_icons/twitter.png" alt=""/></a>
                <a target="_blank" href="https://plus.google.com/u/0/102501578978224362003"><img class="rotate" src="public/img/website/social_icons/google.png" alt=""/></a>
                <a target="_blank" href="http://www.linkedin.com/profile/view?id=123402541&trk=nav_responsive_tab_profile"><img class="rotate" src="public/img/website/social_icons/linkedin.png" alt=""/></a>
                <a target="_blank" href="https://github.com/refaelgold/"><img class="rotate" src="public/img/website/social_icons/github.png" alt=""/></a>
            </ul>
        </div>
    </div>
</div>