<div class="container bubble">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mainTitle">Nir Goldman - Web Master</h1>
        </div>
    </div>





    <div class="row">
        <div class="col-lg-8">
            <p>
                My name is Nir Goldman  and i work as Web developer for 2 years from now.i'm really looking for a company who think big and
                leading the way . I really like to study and explore every new feature who come to the market and for this time i focus on:
            </p>

            <ul>
                <li>Zend framework 2</li>
                <li>Doctrine 2</li>
            </ul>

            <p>
                I'm a fan of Open Source and i believe about not reinventing the wheel when we programming and march to the future.
                I'm looking for a job who think big and grow with them to the end(or at least until the exit :-) )
            </p>





        </div>
        <div class="col-lg-1"></div>
        <div class="col-lg-2">
            <img class="circular" src="public/img/website/profile_pic.png" alt=""/>
        </div>
        <div class="col-lg-1"></div>
    </div>


    <div class="row">
        <span class="col-lg-4">
            <h2 class="paddingLeft5px">Wanna see the Code? </h2>
        </span>
        <span class="col-lg-2"></span>

        <span class="col-lg-5">

        <a target="_blank" href="https://github.com/refaelgold/zf2project">
                <img src="/public/img/website/index/fork-my-button.png" alt="github zf2 project"/>
            </a>
        </span>
    </div>




    <div class="row techLogo">
        <div class="col-lg-12">
            <h2 class="paddingLeft5px">the Technologies on Server-Side are : </h2>
            <ul>
                <li>
                    <img src="public/img/website/index/zendframework-2-logo.png" alt="zendframework"/>
                    <img src="public/img/website/index/php-logo.png" alt="php"/>
                    <img src="public/img/website/index/mysql-logo.png" alt="mysql"/>
                    <img src="public/img/website/index/apache-logo.png" alt="apache"/>

                    <img src="public/img/website/index/doctrine-logo.png" alt="doctrine"/>
                </li>
            </ul>

            <h2 class="paddingLeft5px">the Technologies on Client-Side are : </h2>
            <ul>
                <li>
                    <img src="public/img/website/index/html5-logo.png" alt="html5"/>
                    <img src="public/img/website/index/css3-logo.png" alt="css3"/>
                    <img src="public/img/website/index/jquery-logo.png" alt="jquery"/>
                    <img src="public/img/website/index/sass-logo.png" alt="sass"/>
                    <img src="public/img/website/index/coffeescript-logo.png" alt="coffeescript"/>
                    <img src="public/img/website/index/bootstrap.png" alt="bootstrap"/>
                </li>
            </ul>


            <h2 class="paddingLeft5px">The Tools for Develop a Website are : </h2>
            <ul>
                <li>
                    <img src="public/img/website/index/photoshopcc-logo.jpg" alt="photoshop"/>
                    <img src="public/img/website/index/canary-logo.png" alt="canatry"/>
                    <img src="public/img/website/index/github-logo.png" alt="github"/>
                    <img src="public/img/website/index/phpstorm7-logo.png" alt="phpstorm"/>
                    <img src="public/img/website/index/bower-logo.png" alt="bower"/>
                    <img src="public/img/website/index/grunt-logo.png" alt="grunt"/>
                    <img src="public/img/website/index/yeoman-logo.png" alt="yeoman"/>
                </li>
            </ul>

            <h2 class="paddingLeft5px">The OS are : </h2>
            <ul>
                <li>
                    <img src="public/img/website/index/win-logo.png" alt="windows"/>
                    <img src="public/img/website/index/ubuntu-os.png" alt="ubuntu"/>
                    <img src="public/img/website/index/logo-macos.gif" alt="mac"/>
                </li>
            </ul>


        </div>
    </div>
    <div class="row socialIcons">
        <div class="col-lg-12">

            <h2 class="paddingLeft5px">Keep In touch</h2>
            <ul class="inline">
                <a target="_blank" href="https://www.facebook.com/refael.gold.3"><img  src="public/img/website/social_icons/facebook.png" alt=""/></a>
                <a target="_blank" href="skype:refaelgold?call"><img  src="public/img/website/social_icons/skype.png" alt=""/></a>
                <a target="_blank" href="https://twitter.com/refaelgold"><img  src="public/img/website/social_icons/twitter.png" alt=""/></a>
                <a target="_blank" href="https://plus.google.com/u/0/102501578978224362003"><img src="public/img/website/social_icons/google.png" alt=""/></a>
                <a target="_blank" href="http://www.linkedin.com/profile/view?id=123402541&trk=nav_responsive_tab_profile"><img src="public/img/website/social_icons/linkedin.png" alt=""/></a>
                <a target="_blank" href="https://github.com/refaelgold/"><img  src="public/img/website/social_icons/github.png" alt=""/></a>
            </ul>
        </div>
    </div>

<!--    <div class="row">-->
<!--        <div class="col-lg-1"></div>-->
<!--        <div class="col-lg-10">-->
<!--            <h2 class="greenShadowHeadline forcePointer">That's All folks.Happy Coding !!! :-)</h2>-->
<!--        </div>-->
<!--        <div class="col-lg-1"></div>-->
<!--    </div>-->
</div>