<div class="container bubble">
    <!--will be replaced with the aswame zend form!!!-->
    <div class="row">
        <div class="col-lg-12">
            <h3 class="underline">Zend Framework 2 Kick Start</h3>
        </div>


        <div class="col-lg-6">

            <div class="well">
                <ul>
                    <li>all the website itself its on module who call "Website"</li>
                    <li>this is the Album Module from Zend Framework 2  tuts but has you can see its on hebrew translate with .po file and View Manager<a href="<?php echo $this->url('album', array('action' => 'index')); ?>">Album module In Hebrew Translate</a></li>
                    <li>this is the Start-tech Module <a href="<?php echo $this->url('start-tech', array('action' => 'index')); ?>">Start-tech module</a></li>
                    <li>This module is a Quiz from SpotOption -Must login from 404 page(green link at the bottom) <a href="<?php echo $this->url('SpotOption', array('action' => 'index')); ?>">SpotOption module</a></li>
                </ul>
            </div>
        </div>
</div>