<?php
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath().'/public');
} ?>


<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Hanukkah CMS'. $this->translate('Home'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>


        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/auth-doctrine/layout/zf2_fav.png'))
                        ->prependStylesheet($this->basePath() . '/css/auth-doctrine/style.css')
                        ->prependStylesheet($this->basePath() . '/css/global.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/flexslider.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/normalize.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/auth-doctrine/general.js')
            ->prependFile($this->basePath() . '/js/polyfills.js')
            ->prependFile($this->basePath() . '/js/modernizr-2.6.2.min.js')
            ->prependFile($this->basePath() . '/js/jquery.flexslider-min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>

    </head>
    <body id="layoutTemplateWrappercms" >


        <nav class="navbar  navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>


                    <a class="navbar-brand" href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login'));?>">
                        <div class="logo"></div>
                        <div class="logoCaption">Hanukkah CMS</div>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>


            <?php echo $this->content; ?>

        </div> <!-- /container -->
        <footer class="background-subtle-white-feathers">
            <!--                    <h1>this is the Right Place !!</h1>-->
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
