<?php
// module/Album/view/album/album/delete.phtml:



$title = 'Delete album';

$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>

<p>
  <?php echo $this->translate('Are you sure that you want to delete');?>

    '<?php echo $this->escapeHtml($album->title); ?>'
    <?php echo  $this->translate('by');?>
    '<?php echo $this->escapeHtml($album->artist); ?>'?
</p>
<?php
$url = $this->url('album', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int)$album->id; ?>" />
        <input type="submit" name="del" value="<?php echo $this->translate('Yes');?>" />
    </div>
</form>