
<?php

//http://framework.zend.com/apidoc/2.0/classes/Zend.Db.ResultSet.ResultSet.html


/*
 * this View checks if the album have a tracks by the API of zend framework on the link below
 *
 * if there is a track on the album- we get the songs
 *
 * else we get a redirect to homepage(album)
*/

?>


<table class="table">
    <tr class="table-main-title">

        <td><?php echo $this->translate('Track Id')?></td>
        <td><?php echo $this->translate('Track')?></td>
    </tr>
    <?php foreach ($tracks as $track) : ?>
        <tr>
            <td ><?php echo $this->escapeHtml($track->track_number);?></td>
            <td><?php echo $this->escapeHtml($track->track_title);?></td>
        </tr>
    <?php endforeach; ?>
</table>


<a href="<?php echo $this->url('album', array('action'=>'addNewTrack','id'=>$id));?>" >
    <?php echo $this->translate('Add New song')?>
</a>



