<div class="textAlignCenter">
    <h2>
    <?php echo $this->message; ?>
    </h2>

    <hr />


    <hr />
        <a class="mainBtn" id="newCustomerBtn" href="<?php echo $this->url('SpotOption', array('controller' => 'call','action' => 'new',  'id' => $customerId)); ?>">New Call</a>
    <hr />

    <h2>
        <span>Hello , </span>
        <span>


            <?php
            foreach($specificCustomer as $Customer)
                echo $Customer->getFirstName();
            echo " ";
                echo $Customer->getLastName();
            ?>


        </span>
        <br/>
        <span>this list represents all your calls : </span>
    </h2>
</div>
<table class="bordered">
    <tr>
        <th>Subject</th>
        <th>Content</th>
        <th>Options</th>
    </tr>

    <?php foreach ($calls as $call) { ?>
    <tr>
        <td><?php echo $this->escapeHtml($call->getSubject());?></td>
        <td><?php echo $this->escapeHtml($call->getContent());?></td>
        <td>
            <a href="<?php echo $this->url('SpotOption', array('controller' => 'call','action' => 'edit' ,  'id' => $call->getId())); ?>">Edit</a>
            <span> | </span>
            <a href="<?php echo $this->url('SpotOption', array('controller' => 'call','action' => 'delete', 'id' => $call->getId())); ?>" onclick="return confirm('Are you sure?')">Delete</a>
        </td>
        <?php } ?>
</table>
