    <div class="wrapper404All">
        <div class="wrapper404">
        <div id="rocket"></div>

        <hgroup>
            <h1>Page Not Found</h1>
            <h2>We couldn't find what you were looking for.</h2>
            <h2><a href="<?php echo $this->url('auth-doctrine', array('controller'=>'index','action' => 'index')); ?>">Login</a></h2>
        </hgroup>
    </div>
    <div class="blackDummyDiv"></div>
</div>